# Generated by Django 3.0.9 on 2023-10-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ['-created']},
        ),
    ]
